### ISSUE TITLE
Catching all IOErrors when getting images

### ISSUE THREAD

**Issue by prydie** [mariocesar/sorl-thumbnail#355]
[`sorl.thumbnail.base.get_thumbnail()`](https://github.com/mariocesar/sorl-thumbnail/blob/master/sorl/thumbnail/base.py#L62) catches all `IOError`s and logs a rather unhelpful (in many cases) error `Remote file [%s] at [%s] does not exist`. 

There are many reasons why this function may fail (in my case `urlopen` was failing due to Python not picking up the SSL certificate store on FreeBSD).

It would be more helpful to catch the exception and use `logger.exception()` to give developers better insight into what's actually going on under the hood.

**Comment by relekang** [comment]
That sounds like a good idea :)
