### ISSUE TITLE
Replace SortedDict with OrederedDict: SortedDict removed in Django 1.8

### ISSUE THREAD

**Issue by jamespacileo** [mariocesar/sorl-thumbnail#360]
Deprecated in Django 1.7

Link to docs:
https://docs.djangoproject.com/en/1.7/ref/utils/#django.utils.datastructures.SortedDict

SortedDict has been removed from Django 1.8, which will cause sorl-thumbnail not to work anymore.

Needs replacing with OrderedDict as suggested in the docs.

**Comment by yourcelf** [comment]
SortedDict is still present in Django 1.8, but will be removed in 1.9.

It still should be fixed, but at least it still function in 1.8 (albeit with a warning).

**Comment by SalahAdDin** [comment]
Fix please :+1:
