### ISSUE TITLE
Sorl-thumbnail is generating thumbnails in wrong size.

### ISSUE THREAD

**Issue by miratcan** [mariocesar/sorl-thumbnail#366]
I have an image here, i uploaded it to dropbox with same name at server:

https://www.dropbox.com/s/q2v8b7jrznyvh68/aaacc6460e2e4a0aa653fa8bbaa59f61?dl=0

The problem is, i'm getting thumbnail of this image with this command:

    thmb = get_thumbnail(img, '220')

Expecting that thumbnail width will be 220, but...

    > thmb.width
    70

Original image size is 1836 × 3264 pixels. Size of thumbnail should be:

    ratio = 220 / 1836 = 0.11982570806100218
    (1836 * ratio)X(3264 * ratio) =  220X391 pixels.

But sorl-thumbnail is giving me 70x124 image. I followed source code of sorl-thumbnail and last line in this function looked suspicious for me:

    # base.py:63
    def _calculate_scaling_factor(self, x_image, y_image, geometry, options):
        crop = options['crop']
        factors = (geometry[0] / x_image, geometry[1] / y_image)
        return max(factors) if crop else min(factors)

If crop is not given,  function is returning "desired_thumbnail_height / y_image" then, new image width and height is calculated by multiplying source_image_width with factor. 

Am i missing something or this _calculate_scaling_factor method is behaving wrong. I think it must return geometry[0] / x_image if there is no height given.

**Comment by frankier** [comment]
Can you try specifying the geometry as "220x"? I believe this should fix the problem.

**Comment by mariocesar** [comment]
@miratcan if you use `thmb = get_thumbnail(img, '220x')` that will fix the issue

**Comment by miratcan** [comment]
> @miratcan if you use thmb = get_thumbnail(img, '220x') that will fix the issue

then, it must force me to use that syntax.
