### ISSUE TITLE
After clear+cleanup, duplicate thumbnails generated infinitely

### ISSUE THREAD

**Issue by pa-jama** [mariocesar/sorl-thumbnail#375]
using sorl-thumbnail==11.12.1b, django 1.6

I did thumbnail clear, then thumbnail cleanup management commands.
I noticed performance decrease, and then all the cpu was maxed out.

root@sv:~# ls -lrt /cache/01/dd/01ddda3753198b3450ed2f84d5e15e* | head
cache/01/dd/01ddda3753198b3450ed2f84d5e15e90.jpg
cache/01/dd/01ddda3753198b3450ed2f84d5e15e90_1.jpg
root@sv:~# ls -lrt /cache/01/dd/01ddda3753198b3450ed2f84d5e15e* | tail
cache/01/dd/01ddda3753198b3450ed2f84d5e15e90_13503.jpg
cache/01/dd/01ddda3753198b3450ed2f84d5e15e90_13504.jpg

    mysql> select * from thumbnail_kvstore where value like '%3753198b3450ed2f84d5e15%' order by value limit 10;
 
    | sorl-thumbnail||image||bfc5b275575719860feae052c26ffbff | {"storage": "django.core.files.storage.FileSystemStorage", "name": "cache/01/dd/01ddda3753198b3450ed2f84d5e15e90_1.jpg", "size": [138, 85]}     |
    | sorl-thumbnail||image||42084b2fc2a01e5d314e4e4dca438e37 | {"storage": "django.core.files.storage.FileSystemStorage", "name": "cache/01/dd/01ddda3753198b3450ed2f84d5e15e90_10.jpg", "size": [138, 85]}    |
    | sorl-thumbnail||image||c28a48632513437b92f5e385ac91cde9 | {"storage": "django.core.files.storage.FileSystemStorage", "name": "cache/01/dd/01ddda3753198b3450ed2f84d5e15e90_100.jpg", "size": [138, 85]}   |
    | sorl-thumbnail||image||ab6d0393e88919f6c23d4049b8f57938 | {"storage": "django.core.files.storage.FileSystemStorage", "name": "cache/01/dd/01ddda3753198b3450ed2f84d5e15e90_1000.jpg", "size": [138, 85]}  |
    | sorl-thumbnail||image||3e0247a2ef8ae84816b5eb1fe2e80b32 | {"storage": "django.core.files.storage.FileSystemStorage", "name": "cache/01/dd/01ddda3753198b3450ed2f84d5e15e90_10000.jpg", "size": [138, 85]} |
    | sorl-thumbnail||image||d1c9093e9248212e605230490485ff3b | {"storage": "django.core.files.storage.FileSystemStorage", "name": "cache/01/dd/01ddda3753198b3450ed2f84d5e15e90_10001.jpg", "size": [138, 85]} |
    | sorl-thumbnail||image||e6acce2c173d9fea454660e92bd2fee2 | {"storage": "django.core.files.storage.FileSystemStorage", "name": "cache/01/dd/01ddda3753198b3450ed2f84d5e15e90_10002.jpg", "size": [138, 85]} |
    | sorl-thumbnail||image||9ffaaa02b8ec89ac729b8992eb9831d0 | {"storage": "django.core.files.storage.FileSystemStorage", "name": "cache/01/dd/01ddda3753198b3450ed2f84d5e15e90_10003.jpg", "size": [138, 85]} |
    | sorl-thumbnail||image||2ca07aae65aca3061d54bc20f97a9768 | {"storage": "django.core.files.storage.FileSystemStorage", "name": "cache/01/dd/01ddda3753198b3450ed2f84d5e15e90_10004.jpg", "size": [138, 85]} |
    | sorl-thumbnail||image||4c6855773caf15495547affdf6a7a9f9 | {"storage": "django.core.files.storage.FileSystemStorage", "name": "cache/01/dd/01ddda3753198b3450ed2f84d5e15e90_10005.jpg", "size": [138, 85]} |

For just one file, 13500 were generated so far. 
Pages were taking 10-20 seconds to render due to sorl thumbnail generating thumbnails infinitely.

I'm not sure what caused it, but I fixed it by - 
1)completley clearing thumbnail_kvstore table,
2) deleting all cached files
2)rerunning ./manage.py thumbnail clear, ./manage.py thumbnail cleanup.

**Comment by frankier** [comment]
This was fixed in https://github.com/mariocesar/sorl-thumbnail/commit/0dd77e6fb75966f064ddc05e8547fe1bfb5e938e

Run a newer release.

**Comment by frankier** [comment]
PS here is the previous bug report: https://github.com/mariocesar/sorl-thumbnail/issues/312

**Comment by pa-jama** [comment]
Thanks! This was a huge headache for me. What is the best way to get rid of the duplicates that have been created? 
Should I run clear or cleanup again?

**Comment by frankier** [comment]
I had the same problem and I extended the management command to help clean up afterwards too:

./manage.py thumbnail clear_delete_all

Careful because this will just delete everything in the thumbnail cache directory. If you don't want to regenerate the thumbnails again you might have to some command line stuff using the Unix find command to delete files matching *_<number>.jpg.

**Comment by pa-jama** [comment]
That is cool, I was trying to clear everything in the first place.
Thanks.
