### ISSUE TITLE
Drop support for Django 1.4, 1.5 and 1.6

### ISSUE THREAD

**Issue by caioariede** [mariocesar/sorl-thumbnail#388]
Is there a planned date to remove support for older versions of Django?

I was thinking that we could drop the support for older versions following the [schedule for LTS versions](https://www.djangoproject.com/download/). So after October 1, 2015 we could drop the support for Django 1.4, 1.5 and 1.6. Basically, removing them from our tests (tox / travis).

What do you guys think?

**Comment by mariocesar** [comment]
Makes sense, follow the Django support dates is Ok

**Comment by timgraham** [comment]
PR: https://github.com/mariocesar/sorl-thumbnail/pull/459
