### ISSUE TITLE
How to specify height only and let width scale automatically without cropping?

### ISSUE THREAD

**Issue by variable** [mariocesar/sorl-thumbnail#389]
As title, this is what I have currently

    {% thumbnail competition.photo "850x475" padding=True as im %}

but this crops the photo in height, what I want is just specify 457, and let it to scale to whatever width. Is it possible?

**Comment by mariocesar** [comment]
```{% thumbnail competition.photo "x475" padding=True upscale=True as im %}```

**Comment by variable** [comment]
Sorry it still crops the image instead of shrinking it to fit.
