### ISSUE TITLE
ImageFile URL missing location

### ISSUE THREAD

**Issue by fjcaetano** [mariocesar/sorl-thumbnail#391]
I'm running on Heroku and using S3Boto as storage these are some of my settings:

``` python
DEFAULT_FILE_STORAGE = 'bach_admin.s3utils.MediaRootS3BotoStorage'
STATICFILES_STORAGE = 'bach_admin.s3utils.StaticRootS3BotoStorage'
THUMBNAIL_PREFIX = 'media/cache/'
MEDIA_URL = 'http://myS3bucket.com/media/'
```

The issue is when an ImageFile object is created its initializer receives a name like `media/cache/90/...` and checks the storage's location to trim it from the name. The resulting name is `cache/90/...`.

When the ImageFile `url` getter is called it passes that trimmed name to the storage which doesn't include its location instead of using `settings.MEDIA_URL`. This resulting url is something like `http://myS3bucket.com/cache/90/...` without the `media` path in it.

I have tried changing `THUMBNAIL_PREFIX` with no success. I can't change `MEDIA_URL` because it will break everything else. Am I doing something wrong? Is there any setting I'm missing?

**Comment by caioariede** [comment]
This might be what you're looking for: http://stackoverflow.com/questions/12659655/django-storages-sorl-thumbnail-s3-not-working-well-together-urls-mismatch

This isn't an issue with sorl-thumbnail, but with the way django-storages s3boto backend works.

**Comment by fjcaetano** [comment]
Thank you @caioariede. I managed to make it work by setting `AWS_LOCATION = 'media/'`
