### ISSUE TITLE
sorl-thumbnail does not save photo or save to key/value store

### ISSUE THREAD

**Issue by enkitosh** [mariocesar/sorl-thumbnail#403]
Hi I'm having a weird problem. sorl-thumbnail does not report any errors for this, I have TUMBNAIL_DEBUG = TRUE. When I call get_thumbnail like so

    thumb = get_thumbnail(image, '100x100')

I actually get a result. And if I then request the url

    >>> thumb.url
    >>> '/media/cache/54/88/5488098dc3e08824918a06aff19b6962.jpg'

I get an url. But when I look for this image at the location it tells me, I find no photo.
Also I check for keys in redis database, nothing. 
I originally thought this was some kind of key/value store conflict because I'm using
redis for caching as well, so I moved thumbnail redis to another server. But this does not change anything.
My configs?
I just have THUMBNAIL_REDIS_HOST set with the ip I'm pointing it towards
otherwise my configs have default settings, 6379 as port and 0 as redis-db

**Comment by tonimichel** [comment]
I am experiencing a similar issue. In most cases, the scaled images are created on disk, but sometimes, they are not. I am also using the ``get_thumbnail`` method, not the template tag.

I dont have any special config, except a custom Storage Backend, which only refines the storage location.

<pre>
class Storage(FileSystemStorage):

    def __init__(self, *args, **kwargs):
        super(Storage, self).__init__(*args, **kwargs)
        self.location = settings.CUSTOME_FILE_STORAGE_PATH

</pre>

**Comment by enkitosh** [comment]
I'm not sure what this was but after restarting redis and cleaning up obvious javascript errors in my code I got it working again. I'm closing this @tonimichel I hope you are fine with this, feel free to open it again if you still have this issue.
