### ISSUE TITLE
TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by pacahon** [mariocesar/sorl-thumbnail#414]
Hello. Is it a normal behaviour?
My requirements.txt:
```
sorl-thumbnail==12.3
Django==1.8.5
```

Actions to do:
* upload image
* delete image from `media/` folder, delete cached thumbnail file (I have some missed pictures on my site, so I trying to emulate this scenario)
* run `./manage.py thumbnails clear/cleanup`
* try to load admin model detail page

After that I have an error:
```
TypeError: 'NoneType' object has no attribute '__getitem__'
```

part of Traceback related to problem:
```
File "/Users/pacahon/.pyenv/versions/csc/lib/python2.7/site-packages/sorl/thumbnail/admin/current.py", line 44, in render
    ) % (mini.width, value.url, mini.url, output)
File "/Users/pacahon/.pyenv/versions/csc/lib/python2.7/site-packages/sorl/thumbnail/images.py", line 53, in width
    return self.size[0]
```

I don't expect errors in that case. With `DEBUG=True` I got a Traceback. With disabled I can't see image field at all. Any suggestions how to avoid this?

**Comment by andrealencar** [comment]
Helo,
I'm exactly the same problem, even with the debug = False the field does not appear on the form.

**Comment by pacahon** [comment]
@andrealencar Hello, I've investigated a problem little bit, you can add `THUMBNAIL_DUMMY=True` to show dummy image instead of IOError Exception.
Also, you can play with `THUMBNAIL_DUMMY_SOURCE` and `THUMBNAIL_DUMMY_RATIO` settings.

https://github.com/mariocesar/sorl-thumbnail/blob/master/sorl/thumbnail/conf/defaults.py#L94

**Comment by OlivierGaillard** [comment]
Thanks for the tip setting THUMBNAIL_DUMMY! I had the same problem after a migration.
