### ISSUE TITLE
Does not create thumbnail from a specific jpeg (while from others does)

### ISSUE THREAD

**Issue by okrutny** [mariocesar/sorl-thumbnail#429]
I got a few pictures which I upload from django admin using solr.thumbnail.ImageField and it works perfectly - image is uploaded to media folder, thumbnails are created in cache subdir and proper entries in thumbnail_kvstore are created.

I got some images though, which do not work though - they are uploaded to media folder, but no cache entries and no thumbnails are created. No errors or anything raised.

Django==1.8
Pillow==3.0.0
sorl-thumbnail==12.3

This picture I obtained from bigger one and resizing down, but same behaviour applies to original picture also.
What should I look into to make those pictures work?

![aaa](https://cloud.githubusercontent.com/assets/2536571/12032934/07152fec-ae1e-11e5-8985-f36039426d8e.jpg)

**Comment by mariocesar** [comment]
This is a backend specific issue,

will you able to find a solution?

**Comment by okrutny** [comment]
There is a problem with exif tags:

```
{315: u'J.F.', 296: 2, 34665: 264, 306: u'2015:08:06 22:06:45', 271: u'Canon', 272: u'Canon EOS 5D Mark III', 305: u'Adobe Photoshop CS6 (Macintosh)', 274: 1, 33432: u'Jakub Frackowiak', 282: 300.0, 283: 300.0}
```
and how they are being processed by PIL/TiffImagePlugin.__get__item method, which is used by PIL/JpegImagePlugin._get_exif()

```
    def __getitem__(self, tag):
        if tag not in self._tags_v2:  # unpack on the fly
            data = self._tagdata[tag]
            typ = self.tagtype[tag]
            size, handler = self._load_dispatch[typ]
            self[tag] = handler(self, data, self.legacy_api)  # check type
        val = self._tags_v2[tag]
        if self.legacy_api and not isinstance(val, (tuple, bytes)):
            val = val,
        return val
```

```
_tags_v2 = {36864: ('0230',), 37377: (6.965784,), 40962: (1440,), 36867: (u'2015:08:05 15:23:36',), 36868: (u'2015:08:05 15:23:36',), 37381: (3.0,), 41990: (0,), 37383: (5,), 37385: (16,), 37386: (118.0,), 37378: (5.655638,), 41486: (1600.0,), 41487: (1600.0,), 37520: (u'00',), 37521: (u'00',), 37522: (u'00',), 40963: (960,), 37380: (0.0,), 33434: (0.008,), 33437: (7.1,), 34850: (1,), 40961: (65535,), 34855: (100,), 41987: (1,)}
```

There is a tag: 42034 which is not in _tags_v2 and because of this "load_rational" handler is called and trying to divide by zero as there are some zeros in vals after upacking data related to this tag.

```
@_register_loader(5, 8)
    def load_rational(self, data, legacy_api=True):
        vals = self._unpack("{0}L".format(len(data) // 4), data)
        combine = lambda a, b: (a, b) if legacy_api else a / b
        return tuple(combine(num, denom)
                     for num, denom in zip(vals[::2], vals[1::2]))
```
with:
```
vals = (70, 1, 200, 1, 0, 0, 0, 0) 
legacy_api = False
```
problem is:
```
  File "/home/mstrecker/envs/papu/local/lib/python2.7/site-packages/PIL/TiffImagePlugin.py", line 482, in <lambda>
    combine = lambda a, b: (a, b) if legacy_api else a / b
ZeroDivisionError: division by zero
```

**Comment by lampslave** [comment]
Try to use Pillow=2.9.3 or [wait for 3.1](https://github.com/python-pillow/Pillow/pull/1492).

**Comment by okrutny** [comment]
many thanks @lampslave - works like a charm on Pillow==3.1.0. If you provide answer to http://stackoverflow.com/questions/34716513/solr-thumbnail-some-jpegs-are-not-processed, I will accept it :)

I think the issue can be closed.

**Comment by hugovk** [comment]
Pillow 3.1.0 was released on 4th January, please upgrade like:

`pip install -U pillow`

**Comment by mariocesar** [comment]
Thank you @hugovk
