### ISSUE TITLE
no migration folder included after installation

### ISSUE THREAD

**Issue by variable** [mariocesar/sorl-thumbnail#436]
Just pip installed the package and found out no migration folder included in the site_package, is this a known issue?

**Comment by mariocesar** [comment]
What version are you using ?

**Comment by variable** [comment]
sorl-thumbnail==12.3

**Comment by mariocesar** [comment]
@variable please try installing the latest ```pip install --pre --upgrade sorl-thumbnail``` or ```pip install sorl-thumbnail==12.4a1```

**Comment by variable** [comment]
pip install sorl-thumbnail==12.4a1 worked

**Comment by mariocesar** [comment]
:+1:

**Comment by variable** [comment]
thanks!
