### ISSUE TITLE
Proposal: Move to Jazzband to expand development efforts

### ISSUE THREAD

**Issue by kevin-brown** [mariocesar/sorl-thumbnail#463]
Quoting from the [Jazzband website](https://jazzband.co/)

> Jazzband is a cooperative experiment to reduce the stress of maintaining Open Source software alone.

We use this project in a few of our applications, and I can see that we're not the only ones using it. I've noticed the backlog of tickets and pull requests, as well as the long time since the latest release.

As a fellow open source maintainer, I understand the added work that goes into maintaining an open source project, especially one that isn't your main focus. That's why I'm proposing that you move (or donate, same idea) the project to Jazzband, to increase the number of possible maintainers of the project.

You can read more about how Jazzband works (and the guidelines for submitting projects) at https://jazzband.co/about/guidelines

**Comment by timgraham** [comment]
I would like to help.

**Comment by camilonova** [comment]
@mariocesar It is so sad to this this project in such state, please move sorl-thumbnail to jazzband so we can improve the speed release cycle.

**Comment by mariocesar** [comment]
@camilonova I'm worried also. 
Will review all this week, now that I have the time.

**Comment by camilonova** [comment]
@mariocesar thank you. If you add me as a repo contributor I can to the whole thing. Let me know soon.

**Comment by hasB4K** [comment]
Move this repository to Jazzband is, I think, and excellent idea! :)

**Comment by SalahAdDin** [comment]
@mariocesar plz.

**Comment by camilonova** [comment]
@mariocesar How it went your review? Can we move forward?

**Comment by mariocesar** [comment]
Will do, 

I was expecting contributors but it feels better to just move out. There are forks with new designs and based on more broad usage scenarios, I was always feeling that sorl.thumbnail could implement those ideas, however it feels that legacy support is more important and critical for most people, I respect that

**Comment by mariocesar** [comment]
@camilonova could you prepare the move? I will authorize the organization change as soon everything is ready

**Comment by Flimm** [comment]
@mariocesar I hugely appreciate the work you do maintaining sorl.thumbnail. I don't know if the step forward is to open this repo to Jazzband, or something else, but I would like to see a situation where you don't have to carry the load by yourself.

Even if this Github repo gets moved to Jazzband, there is still the issue of uploading packages to PyPI. Only aino and mariocesar (who I assume is you) can do that.

**Comment by mariocesar** [comment]
As I understand there is a list of guidelines to comply before moving out, if any current maintainer could help me doing those errands we could move faster 

cc @camilonova

**Comment by mariocesar** [comment]
Discussion moved to -> https://github.com/jazzband/roadies/issues/57
