### ISSUE TITLE
Compatibility issue with newer Django 1.10

### ISSUE THREAD

**Issue by MartinBorg** [mariocesar/sorl-thumbnail#464]
Even after adding `'django.contrib.auth'`, and  `'django.contrib.contenttypes'` to `INSTALLED_APPS` in `tests/settings/default.py` and trying to get `tests/thumbnail_tests/urls.py` in shape for Django 1.10, many tests fail. I probably do not know enough about Django to solve this.

**Comment by timgraham** [comment]
PR: https://github.com/mariocesar/sorl-thumbnail/pull/459

**Comment by MartinBorg** [comment]
Thank you, Tim!

**Comment by timgraham** [comment]
This can be closed now that the PR is merged.
